// Export to HTML
export const exportToHTML = (title, content) => {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - ShellKode MSP Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #f8fafc; color: #1e293b; padding: 30px; }
    .header { background: linear-gradient(135deg, #1e40af, #0891b2); color: white; padding: 30px; border-radius: 12px; margin-bottom: 24px; }
    .header h1 { font-size: 28px; margin-bottom: 6px; }
    .header p { opacity: 0.85; font-size: 14px; }
    .meta { display: flex; gap: 20px; margin-top: 12px; font-size: 13px; }
    .meta span { background: rgba(255,255,255,0.2); padding: 4px 12px; border-radius: 20px; }
    table { width: 100%; border-collapse: collapse; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.08); margin-bottom: 20px; }
    th { background: #1e40af; color: white; padding: 12px 16px; text-align: left; font-size: 13px; font-weight: 600; }
    td { padding: 11px 16px; border-bottom: 1px solid #f1f5f9; font-size: 13px; }
    tr:last-child td { border-bottom: none; }
    tr:nth-child(even) { background: #f8fafc; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700; letter-spacing: 0.5px; }
    .critical { background: #fef2f2; color: #dc2626; border: 1px solid #fecaca; }
    .high { background: #fff7ed; color: #ea580c; border: 1px solid #fed7aa; }
    .medium { background: #fffbeb; color: #d97706; border: 1px solid #fde68a; }
    .low { background: #eff6ff; color: #2563eb; border: 1px solid #bfdbfe; }
    .success { background: #f0fdf4; color: #16a34a; border: 1px solid #bbf7d0; }
    .section { margin-bottom: 32px; }
    .section-title { font-size: 18px; font-weight: 700; color: #1e293b; margin-bottom: 14px; padding-bottom: 8px; border-bottom: 2px solid #e2e8f0; }
    .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 16px; margin-bottom: 24px; }
    .summary-card { background: white; border-radius: 10px; padding: 20px; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }
    .summary-card .value { font-size: 32px; font-weight: 800; }
    .summary-card .label { font-size: 12px; color: #64748b; margin-top: 4px; }
    .footer { text-align: center; margin-top: 40px; padding: 20px; color: #94a3b8; font-size: 12px; border-top: 1px solid #e2e8f0; }
    @media print { body { background: white; padding: 0; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <p>Generated by ShellKode MSP Portal — Team Cronos</p>
    <div class="meta">
      <span>📅 ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</span>
      <span>🕐 ${new Date().toLocaleTimeString('en-IN')}</span>
      <span>🔒 Confidential</span>
    </div>
  </div>
  ${content}
  <div class="footer">
    <p>© ${new Date().getFullYear()} ShellKode Technologies — MSP Operations Portal | Team Cronos</p>
    <p style="margin-top:4px">This report is auto-generated and confidential. Do not distribute without authorization.</p>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.html`;
  a.click();
  URL.revokeObjectURL(url);
};

// Export to CSV (Excel-compatible)
export const exportToCSV = (filename, headers, rows) => {
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${String(cell || '').replace(/"/g, '""')}"`).join(','))
  ].join('\n');

  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
};

// Generate security HTML report content
export const generateSecurityReportHTML = (clientName, data) => {
  const { summary, findings } = data;
  const summarySection = `
    <div class="section">
      <div class="section-title">Executive Summary</div>
      <div class="summary-grid">
        <div class="summary-card"><div class="value" style="color:#dc2626">${summary.critical}</div><div class="label">Critical</div></div>
        <div class="summary-card"><div class="value" style="color:#ea580c">${summary.high}</div><div class="label">High</div></div>
        <div class="summary-card"><div class="value" style="color:#d97706">${summary.medium}</div><div class="label">Medium</div></div>
        <div class="summary-card"><div class="value" style="color:#2563eb">${summary.low}</div><div class="label">Low</div></div>
        <div class="summary-card"><div class="value" style="color:#16a34a">${summary.score}</div><div class="label">Security Score</div></div>
      </div>
    </div>
  `;
  const findingsSection = `
    <div class="section">
      <div class="section-title">Security Findings — ${clientName}</div>
      <table>
        <thead><tr><th>ID</th><th>Severity</th><th>Finding</th><th>Service</th><th>Resource</th><th>Remediation</th></tr></thead>
        <tbody>
          ${findings.map(f => `
            <tr>
              <td style="font-family:monospace">${f.id}</td>
              <td><span class="badge ${f.severity.toLowerCase()}">${f.severity}</span></td>
              <td>${f.title}</td>
              <td>${f.service}</td>
              <td style="font-family:monospace;font-size:11px">${f.resource}</td>
              <td>${f.remediation}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `;
  return summarySection + findingsSection;
};

export const generateCostReportHTML = (clientName, data) => {
  const serviceRows = data.serviceBreakdown.map(s => `
    <tr><td>${s.service}</td><td>$${s.cost}</td><td>${s.percentage}%</td></tr>
  `).join('');
  return `
    <div class="section">
      <div class="section-title">Cost Summary — ${clientName}</div>
      <div class="summary-grid">
        <div class="summary-card"><div class="value" style="color:#2563eb">$${Number(data.totalLastMonth).toLocaleString()}</div><div class="label">Last Month</div></div>
        <div class="summary-card"><div class="value" style="color:#7c3aed">$${Number(data.totalTwoMonthsAgo).toLocaleString()}</div><div class="label">2 Months Ago</div></div>
        <div class="summary-card"><div class="value" style="color:#dc2626">${data.unusedEIPs.length}</div><div class="label">Unused EIPs</div></div>
        <div class="summary-card"><div class="value" style="color:#d97706">${data.oldSnapshots.length}</div><div class="label">Old Snapshots</div></div>
      </div>
    </div>
    <div class="section">
      <div class="section-title">Service Breakdown</div>
      <table>
        <thead><tr><th>Service</th><th>Cost (USD)</th><th>% of Total</th></tr></thead>
        <tbody>${serviceRows}</tbody>
      </table>
    </div>
    <div class="section">
      <div class="section-title">Cost Anomalies</div>
      <table>
        <thead><tr><th>Date</th><th>Service</th><th>Expected</th><th>Actual</th><th>Anomaly Amount</th><th>Severity</th></tr></thead>
        <tbody>
          ${data.anomalies.map(a => `
            <tr>
              <td>${a.date}</td><td>${a.service}</td><td>${a.expectedAmount}</td>
              <td>${a.actualAmount}</td><td style="color:#dc2626;font-weight:700">${a.anomalyAmount}</td>
              <td><span class="badge ${a.severity.toLowerCase()}">${a.severity}</span></td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `;
};
